import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import {createGuidance} from '../src/guidance.js';import{residenceSlots,residenceEvidence}from'../src/residence.js';import{batteryLocations,batterySearchAction}from'../src/battery.js';import{createWasteAssistant}from'../src/waste.js';import{readGeoData}from'../src/geo-data.js';
const civic=JSON.parse(readFileSync(new URL('./fixtures/civic-evidence.json',import.meta.url))),waste=JSON.parse(readFileSync(new URL('./fixtures/waste-evidence.json',import.meta.url))),residenceFixture=JSON.parse(readFileSync(new URL('./fixtures/residence-evidence.json',import.meta.url)));
const yardFixture=JSON.parse(readFileSync(new URL('./fixtures/battery-yards.json',import.meta.url)));
const make=options=>createGuidance({evidence:async t=>structuredClone(civic[t]),residence:async()=>structuredClone(residenceFixture),office:async()=>null,firstSteps:async()=>({available:false}),...options});
async function dialogue(g,questions){let r;for(const question of questions)r=await g({question,contextToken:r?.contextToken});return r;}
for(const [text,group,permit]of [['Ich bin Italiener und habe eine B-Bewilligung','eu_efta','B'],['Ich bin Italienerin, Ausweis C','eu_efta','C'],['Ich habe Bewilligung B',undefined,'B'],['Ich habe ein Baby',undefined,undefined],['Ich komme aus Italien',undefined,undefined],['Ich bin aus Italien',undefined,undefined],['Ich bin deutscher Staatsbürger','eu_efta',undefined],['Ich bin indischer Staatsbürger, B-Bewilligung','other','B'],['Staatsangehörigkeit eines Drittstaats','other',undefined]])test('separate citizenship, origin and permit: '+text,()=>{const s=residenceSlots(text);assert.equal(s.citizenshipGroup,group);assert.equal(s.permitType,permit);});
for(const permit of ['B','C','L'])test('Bern to Zurich with Italian '+permit+' permit returns scoped SEM rule and municipal documents',async()=>{const r=await dialogue(make(),['Ich ziehe aus Bern nach Zürich. Wo melde ich mich an?',`Ich bin Italiener und habe eine ${permit}-Bewilligung. Was muss ich beachten?`]);assert.equal(r.status,'ok',r.answer);assert.equal(r.context.residenceOrigin,'switzerland');assert.equal(r.context.permitType,permit);assert.match(r.answer,/keine neue Bewilligung allein wegen/);assert.match(r.answer,/Ausländerausweis/);assert.ok(r.claims.some(c=>c.sourceUrl.includes('sem.admin.ch')));assert.doesNotMatch(r.answer,/Zürich Süd/);});
test('B without citizenship asks the missing citizenship group, short answer resumes',async()=>{const g=make();let r=await g({question:'Ich ziehe aus Bern nach Zürich und habe eine B-Bewilligung'});assert.equal(r.pending_question.field,'citizenshipGroup');r=await g({question:'Italien',contextToken:r.contextToken});assert.equal(r.context.citizenshipGroup,'eu_efta');assert.match(r.answer,/EU\/EFTA-Ausweis/);});
test('permit received as a later short follow-up preserves citizenship and origin',async()=>{const r=await dialogue(make(),['Ich bin Italiener und ziehe aus Bern nach Zürich. Was muss ich beachten?','Habe Bewilligung B']);assert.equal(r.context.residenceOrigin,'switzerland');assert.equal(r.context.citizenshipGroup,'eu_efta');assert.match(r.answer,/keine neue Bewilligung/);});
test('foreign arrival never gets domestic permit mobility rule',async()=>{const r=await make()({question:'Ich bin Italiener, habe eine B-Bewilligung und ziehe aus Italien nach Zürich. Was muss ich beachten?'});assert.doesNotMatch(r.answer,/keine neue Bewilligung/);assert.equal(r.context.residenceOrigin,'abroad');});
test('third-country B does not inherit EU mobility',async()=>{const r=await make()({question:'Ich bin indischer Staatsbürger mit B-Bewilligung und ziehe aus Bern nach Zürich.'});assert.equal(r.status,'partial');assert.doesNotMatch(r.answer,/keine neue Bewilligung/);assert.match(r.answer,/Kantonswechsel.*geklärt|Kantonswechsel vor dem Umzug/);assert.ok(r.actions.some(a=>a.url.includes('zh.ch')));});
test('SEM outage leaves city guidance and explicitly marks the missing permit rule',async()=>{const r=await make({residence:async()=>({available:false})})({question:'Ich bin Italiener mit B-Bewilligung und ziehe aus Bern nach Zürich.'});assert.equal(r.status,'partial');assert.match(r.answer,/nicht.*bestätigt/);assert.doesNotMatch(r.answer,/keine neue Bewilligung/);assert.match(r.answer,/14 Tagen/);});
test('baby is a family fact, never a B permit',async()=>{const r=await make()({question:'Ich bin Italiener, habe ein Baby und ziehe aus Bern nach Zürich. Was muss ich beachten?'});assert.equal(r.context.withChildren,true);assert.equal(r.context.permitType,null);assert.ok(r.claims.some(c=>c.id==='foreign_civil'));assert.match(r.answer,/Geburtsscheine/);});
test('changed SEM clause cannot produce a remembered legal rule',async()=>{const r=await residenceEvidence({retriever:{retrieve:async()=>({status:'retrieved',doc:{blocks:[{text:'Es gibt neue Regeln.'}]}})}});assert.equal(r.available,false);assert.equal(r.facts.length,0);});
const retail=async()=>({status:'retrieved',url:'https://www.stadt-zuerich.ch/verkaufsstelle',title:'Verkaufsstelle',retrievedAt:'2026-09-25T09:00:00Z',doc:{blocks:[{text:'Grundsätzlich sind die Händler verpflichtet, die nachfolgenden Produkte und Geräte, die sie selbst vertreiben, zurückzunehmen. Im Kaufpreis von Batterien, PET-Getränkeflaschen und Elektrogeräten ist eine vorgezogene Entsorgungs- und Recyclinggebühr enthalten. Deshalb ist der Fachhandel verpflichtet, diese Produkte und Geräte kostenlos zurückzunehmen.'}]}});
const sites=({data,origin})=>batteryLocations({data,origin,read:async()=>structuredClone(yardFixture)});
test('battery locations require both acceptance and municipal household scope',async()=>{const r=await sites({data:readGeoData()});assert.equal(r.results.length,2);for(const p of r.results){assert.deepEqual(p.materials,['Batterien']);assert.ok(Number.isFinite(p.lat));}assert.ok(r.source.passages.some(p=>p.text.includes('Haushaltsbatterien')));});
test('changed acceptance table never invents battery acceptance',async()=>{const r=await batteryLocations({data:readGeoData(),read:async()=>{const d=structuredClone(yardFixture);for(const b of d.doc.blocks)b.text=b.text.replaceAll('Haushaltsbatterien','Andere Stoffe');return d;}});assert.equal(r,null);});
test('battery follow-up preserves address, sorts only the known subset, supplies retailer locator',async()=>{const g=createGuidance({waste:createWasteAssistant({batterySource:retail,batterySites:sites})});const r=await dialogue(g,['Wo kann ich an der Bahnhofstrasse 102 in Zürich Glas entsorgen?','Wo kann ich Batterien am nächsten entsorgen?']);assert.equal(r.context.address,'Bahnhofstrasse 102');assert.equal(r.results.length,2);assert.equal(r.sortMode,'straight_line_subset');assert.equal(r.dataAvailability.verifiedNearestLocation,false);assert.ok(r.results[0].distanceMeters<=r.results[1].distanceMeters);assert.match(r.answer,/Verkaufsstelle kann näher/);assert.ok(r.actions.some(a=>a.url==='https://recycling-map.ch/de/karte?zip=8001'));});
test('battery source failure gives useful external action and no fake locations',async()=>{const a=createWasteAssistant({batterySource:retail,batterySites:async()=>null});const r=await a({question:'Wo Batterien entsorgen in Zürich?'});assert.equal(r.results.length,0);assert.equal(r.status,'partial');assert.ok(r.actions.some(a=>a.url.includes('recycling-map.ch')));});
test('unverified address is not reused as a confirmed battery distance point',async()=>{const a=createWasteAssistant({batterySource:retail,batterySites:sites});let r=await a({question:'Glas an der Bahnhofstrasse 102 in Zürich'});r=await a({question:'Batterien an der Seefeldstrasse 99999',contextToken:r.contextToken});assert.equal(r.context.address,null);assert.ok(r.results.every(p=>p.distanceMeters===undefined));});
test('locator never accepts arbitrary query strings',()=>assert.equal(batterySearchAction('8001&evil=x').url,'https://recycling-map.ch/de/karte'));

test('denied permit is not a positive B slot',()=>assert.equal(residenceSlots('Ich habe keine B-Bewilligung').permitType,null));
test('citizenship correction uses the final statement',()=>assert.equal(residenceSlots('Ich bin nicht Italiener, sondern indischer Staatsbürger').citizenshipGroup,'other'));
test('expired permit does not activate an unconditional mobility answer',async()=>{const r=await make()({question:'Ich bin Italiener, meine B-Bewilligung ist abgelaufen, ich ziehe aus Bern nach Zürich.'});assert.equal(r.status,'partial');assert.doesNotMatch(r.answer,/keine neue Bewilligung/);});
