
const $=s=>document.querySelector(s);const make=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e};
function link(url,title){const a=make('a',title);try{if(new URL(url).protocol!=='https:')return a;}catch{return a;}a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
$('#form').addEventListener('submit',async e=>{e.preventDefault();$('#submit').disabled=true;$('#output').hidden=false;$('#message').textContent='Amtliche Seiten werden abgerufen … das kann bis zu einer Minute dauern.';for(const id of ['#limits','#results','#fallback'])$(id).replaceChildren();$('#metrics').textContent='';
try{const input={query:$('#question').value,language:'de'};if($('#municipality').value)input.municipality=$('#municipality').value;if($('#topic').value)input.topic=$('#topic').value;
const response=await fetch('/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw Error();const data=await response.json();$('#message').textContent=data.message;
for(const text of data.limitations||[]){const p=make('p',text.replace(/^[A-Z_]+: /,''));p.className='notice';$('#limits').append(p);}
for(const hit of data.results||[]){const article=make('article','');article.append(make('h2',hit.title),link(hit.url,hit.authority+' · Originalseite öffnen'),make('p','Abgerufen: '+new Date(hit.retrievedAt).toLocaleString('de-CH')+' · '+(hit.cache==='hit'?'kurzer Zwischenspeicher':'neuer Abruf')));
for(const p of hit.passages){const d=make('details','');d.open=true;d.append(make('summary',p.heading||'Quellentext'),make('blockquote',p.text));if(p.truncated)d.append(make('small','Auszug gekürzt. Vollständigen Kontext auf der Originalseite prüfen.'));article.append(d);}
if(hit.serviceLinks?.length){article.append(make('h3','Weiterführende amtliche Wege'));for(const s of hit.serviceLinks){const p=make('p','');p.append(link(s.url,s.title));article.append(p);}}$('#results').append(article);}
if(!(data.results||[]).length)for(const s of data.sourceLinks||[]){const p=make('p','');p.append(link(s.url,s.title));$('#fallback').append(p);}
if(data.failures?.length)$('#fallback').append(make('p','Nicht alle Quellen konnten gelesen werden. Es werden keine fehlenden Angaben ergänzt.'));
if(data.metrics)$('#metrics').textContent=`${data.results.length} Quelle(n) mit Textbelegen · ${(data.metrics.durationMs/1000).toFixed(1)} s`;
}catch{$('#message').textContent='Abruf fehlgeschlagen. Prüfe, ob das Terminal mit dem Server noch geöffnet ist.';}finally{$('#submit').disabled=false;}});

$('#locations-form').addEventListener('submit',async e=>{e.preventDefault();$('#locations-submit').disabled=true;$('#locations-results').replaceChildren();$('#locations-status').textContent='Sammelstellen werden gesucht …';try{
 const response=await fetch('/locations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postalCode:$('#postal').value,material:$('#material').value})});
 if(!response.ok)throw Error();const data=await response.json();$('#locations-status').textContent=data.message;
 for(const station of data.results||[]){const article=make('article','');article.append(make('h3',station.address),make('p',station.postalCode+' Zürich · '+station.materials.map(m=>m==='Oel'?'Öl':m).join(', ')));$('#locations-results').append(article);}
 if(data.datasetUrl)$('#locations-results').append(link(data.datasetUrl,'Amtlicher Datensatz · '+data.referenceYear));
 if(data.downloadedAt)$('#locations-results').append(make('p','Daten abgerufen: '+new Date(data.downloadedAt).toLocaleString('de-CH')));
 if(data.totalMatches>data.results.length)$('#locations-results').append(make('p',`${data.results.length} von ${data.totalMatches} Treffern angezeigt. Reihenfolge aus dem Datensatz, keine Rangliste nach Entfernung.`));
 }catch{$('#locations-status').textContent='Suche nicht erreichbar. Bitte den lokalen Server prüfen.';}finally{$('#locations-submit').disabled=false;}});


let csrf='',configured=false,busy=false,controller=null;
const toolNames={get_zurich_guidance:'Zürcher Anliegen und nächste Schritte',get_zurich_waste_guidance:'Ort prüfen und Entsorgung klären',get_swiss_moving_coverage:'Unterstützte Orte und Themen',find_swiss_moving_information:'Amtliche Informationen',find_zurich_recycling_points:'Zürcher Sammelstellen'};
const statuses={evidence_available:'Textbelege gefunden',partial:'Belege mit Einschränkungen',ok:'Passende Daten gefunden',needs_clarification:'Rückfrage erforderlich',out_of_scope:'Noch nicht unterstützt',unavailable:'Keine ausreichenden Belege',no_matches:'Keine passenden Datensätze',coverage:'Umfang geprüft',tool_error:'Abruf fehlgeschlagen'};
function ready(value){configured=value;$('#api-state').textContent=value?'Schlüssel hinterlegt':'Schlüssel fehlt';$('#api-state').classList.toggle('ready',value);$('#key-remove').hidden=!value;$('#connection').open=!value;$('#chat-send').disabled=busy||!value;}
function setBusy(value){busy=value;for(const id of ['#key-save','#key-remove','#chat-reset'])$(id).disabled=value;$('#chat-send').disabled=value||!configured;$('#chat-stop').hidden=!value;$('#chat-question').disabled=value;}
async function api(path,input){const res=await fetch(path,input===undefined?{cache:'no-store'}:{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(input)});const data=await res.json().catch(()=>({message:'Server nicht erreichbar. Bitte das Startfenster prüfen.'}));if(!res.ok)throw Error(data.message||'Anfrage fehlgeschlagen.');return data;}
function inline(parent,text){
  const pattern=/\[([^\]\n]+)\]\((https:\/\/[^\s)]+)\)|(https:\/\/[^\s<>]+)|\*\*([^*\n]+)\*\*/g;let end=0;
  for(const m of text.matchAll(pattern)){parent.append(document.createTextNode(text.slice(end,m.index)));if(m[1])parent.append(link(m[2],m[1]));else if(m[3]){const url=m[3].replace(/[.,;:)]+$/,'');parent.append(link(url,url),document.createTextNode(m[3].slice(url.length)));}else parent.append(make('strong',m[4]));end=m.index+m[0].length;}parent.append(document.createTextNode(text.slice(end)));
}
function format(parent,text){
  // A small Markdown subset, built exclusively with text nodes. No generated HTML.
  parent.replaceChildren();let list=null;
  for(const line of String(text).split('\n')){if(!line.trim()){list=null;continue;}const heading=line.match(/^#{1,4}\s+(.+)/),item=line.match(/^\s*(?:[-*]|\d+\.)\s+(.+)/);if(heading){list=null;const h=make('h3','');inline(h,heading[1]);parent.append(h);}else if(item){if(!list){list=make('ul','');parent.append(list);}const li=make('li','');inline(li,item[1]);list.append(li);}else{list=null;const p=make('p','');inline(p,line);parent.append(p);}}
}
function bubble(who,text){const article=make('article','');article.className='bubble '+who;const speaker=make('div',who==='user'?'Du':'Apertus');speaker.className='speaker';const body=make('div','');body.className='answer-text';format(body,text);article.append(speaker,body);$('#chat-log').append(article);$('#chat-welcome').hidden=true;return article;}
function renderReply(article,data){
  format(article.querySelector('.answer-text'),data.answer);const traces=data.traces||[];if(data.answerOrigin==='structured_mcp')article.querySelector('.speaker').textContent='Swiss Grounding · belegte Auskunft';
  if(data.answerOrigin==='apertus_verified_composition')article.querySelector('.speaker').textContent='Apertus · aus geprüften Fakten zusammengestellt';
  if(data.answerOrigin!=='apertus_verified_composition'&&traces.some(t=>t.cards?.length)){format(article.querySelector('.answer-text'),data.answer.split('\n\n')[0]);for(const t of traces)for(const c of t.cards||[]){const card=make('section','');card.className='guidance-card';card.append(make('h3',c.title));const list=make('ul','');for(const item of c.items){const li=make('li','');inline(li,item);list.append(li);}card.append(list);article.append(card);}}
  if(data.formulation?.requested){
    const original=make('details','');original.className='server-original';original.append(make('summary','Geprüfte Serverantwort und strukturierte Fakten'));const body=make('div','');format(body,data.originalAnswer||data.answer);original.append(body);if(data.serverResult)original.append(make('pre',JSON.stringify(data.serverResult,null,2)));article.append(original);
    if(data.formulation.status.startsWith('fallback_'))article.append(make('small','Die sprachliche Aufbereitung war nicht verfügbar oder erfüllte die Faktenprüfung nicht. Du siehst die belegte Serverantwort.'));
  }
  for(const t of traces){if(t.actions?.length){const box=make('div','');box.className='service-actions';for(const a of t.actions)box.append(link(a.url,a.label));article.append(box);}if(t.locations?.some(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)))article.append(locationMap(t));if(t.status==='needs_clarification'){const hint=make('p','Wähle eine Antwort oder schreibe sie unten ins gleiche Eingabefeld. Bestätigte Angaben bleiben in diesem Gespräch erhalten.');hint.className='clarification';article.append(hint);}if(t.options?.length){const choices=make('div','');choices.className='quick-replies';for(const option of t.options)choices.append(quickReply(option,option));article.append(choices);}if(t.followUp)article.append(quickReply(t.followUp.label,t.followUp.question));for(const suggestion of t.suggestions||[])article.append(quickReply(suggestion.label,suggestion.question));}
  const places=new Map();for(const t of traces)for(const p of t.locations||[])places.set(p.postalCode+'|'+p.address,p);
  if(places.size){const box=make('div','');box.className='locations';box.append(make('h3','Standorte aus dem amtlichen Datensatz'));for(const p of places.values()){const row=make('div','');row.className='place';row.append(make('strong',p.name?p.name+' · '+p.address:p.address),make('small',p.postalCode+' Zürich'+(p.district?' · Kreis '+p.district:'')+' · '+p.materials.map(m=>m==='Oel'?'Öl':m).join(', ')+(Number.isFinite(p.distanceMeters)?' · ca. '+p.distanceMeters+' m Luftlinie':'')));if(p.mapUrl)row.append(link(p.mapUrl,'Punkt in OpenStreetMap öffnen'));box.append(row);}box.append(make('small',traces.some(t=>['city_subset','straight_line_subset'].includes(t.sortMode))?'Gezeigte Auswahl städtischer Recyclinghöfe; keine vollständige Liste aller Batterie-Annahmestellen.':traces.some(t=>t.sortMode==='straight_line')?'Sortierung nach Luftlinie ab der bestätigten Adresse. Keine Fussweg- oder Öffnungszeitenbewertung.':'Übersicht im gewählten Kreis oder PLZ-Gebiet. Für eine Nähe-Suche bitte Strasse und Hausnummer nennen.'));article.append(box);}
  const sources=new Map();for(const t of traces){for(const s of t.sources||[])sources.set(s.url,s);for(const url of t.urls||[])if(!sources.has(url))sources.set(url,{url,title:'Amtlicher Datensatz',retrievedAt:t.dataset?.downloadedAt});}
  if(sources.size){const cards=make('details','');cards.className='sources';cards.append(make('summary','Quellen und Belege ('+sources.size+')'));for(const s of sources.values()){const card=make('div','');card.className='source-card';card.append(link(s.url,s.title||'Originalquelle'));if(s.authority)card.append(make('small',s.authority));if(s.retrievedAt)card.append(make('p','Abgerufen: '+new Date(s.retrievedAt).toLocaleString('de-CH')));if(s.passages?.length){const details=make('details','');details.append(make('summary','Textbelege ansehen'));for(const p of s.passages){details.append(make('strong',p.heading||'Quellentext'),make('blockquote',p.text),make('small','Passage '+p.id+(p.truncated?' · Auszug gekürzt':'')));}card.append(details);}cards.append(card);}article.append(cards);}
  for(const limit of new Set(traces.flatMap(t=>t.status==='needs_clarification'?[]:t.limitations||[]))){const note=make('p',limit.replace(/^[A-Z_]+: /,''));note.className='notice';article.append(note);}
  if(!traces.some(t=>t.status==='needs_clarification')){const note=make('p',traces.some(t=>t.evidence)?'Belege wurden abgerufen. Prüfe wichtige Angaben an der Originalquelle.':'Für diese Frage wurden keine Sachbelege geliefert. Beachte den Hinweis auf die Datenlücke.');note.className='result-note';article.append(note);}
  const details=make('details','');details.className='trace';details.append(make('summary','Abruf nachvollziehen'));for(const t of traces){details.append(make('p',`${toolNames[t.name]||t.name}: ${statuses[t.status]||t.status}`),make('code',t.name),make('small',t.initiatedBy==='application_fallback'?'Aufruf durch die Anwendung abgesichert: Apertus hatte keinen Werkzeugaufruf geliefert.':'Aufruf von Apertus angefordert.'));}if(data.metrics){const m=data.metrics;details.append(make('p',`${m.toolCalls} Werkzeugaufruf(e) · ${m.modelCalls} Modellanfrage(n) · ${(m.durationMs/1000).toFixed(1)} s`));if(m.inputTokens!==null)details.append(make('p',`${m.inputTokens} Eingabe-Token · ${m.outputTokens} Ausgabe-Token (vom Anbieter gemeldet)`));}article.append(details);
}
function clearChat(){$('#chat-log').replaceChildren();$('#chat-welcome').hidden=false;$('#chat-question').value='';}
$('#key-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const key=$('#api-key').value.trim();if(!key)return;$('#key-save').disabled=true;$('#key-status').textContent='Schlüssel wird hinterlegt …';try{await api('/api/key',{key});clearChat();ready(true);$('#key-status').textContent='Schlüssel hinterlegt. Deine erste Frage prüft den Zugang zu Apertus.';$('#chat-status').textContent='Bereit. Schreibe deine Frage oder wähle ein Beispiel.';$('#chat-question').focus();}catch(error){$('#key-status').textContent=error.message;}finally{$('#api-key').value='';$('#key-save').disabled=false;}});
$('#key-remove').addEventListener('click',async()=>{try{await api('/api/disconnect',{});clearChat();ready(false);$('#key-status').textContent='Schlüssel aus dieser Sitzung entfernt.';$('#chat-status').textContent='Bitte einen Swisscom-Schlüssel hinterlegen.';}catch(e){$('#key-status').textContent=e.message;}});
$('#chat-reset').addEventListener('click',async()=>{try{await api('/api/reset',{});clearChat();$('#chat-status').textContent='Neues Gespräch.';$('#chat-question').focus();}catch(e){$('#chat-status').textContent=e.message;}});
for(const button of document.querySelectorAll('[data-question]'))button.addEventListener('click',()=>{if(busy)return;$('#chat-question').value=button.dataset.question;$('#chat-question').focus();$('#chat-form').scrollIntoView({block:'nearest',behavior:'smooth'});});
$('#chat-question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!busy&&configured)$('#chat-form').requestSubmit();}});
$('#chat-stop').addEventListener('click',()=>controller?.abort());
$('#chat-form').addEventListener('submit',async e=>{
  e.preventDefault();if(busy)return;if(!configured){$('#connection').open=true;$('#api-key').focus();return;}const question=$('#chat-question').value.trim();if(!question)return;
  for(const old of document.querySelectorAll('#chat-log .quick-reply'))old.disabled=true;
  bubble('user',question);const reply=bubble('assistant','Deine Frage wird geprüft …');$('#chat-question').value='';setBusy(true);controller=new AbortController();let answerReceived=false,streamError='';$('#chat-status').textContent='Apertus wird angefragt …';
  const receive=event=>{if(event.event==='status')$('#chat-status').textContent=event.message;if(event.event==='trace'){const t=event.trace;$('#chat-status').textContent=t.event==='start'?(toolNames[t.name]||t.name)+' werden abgerufen …':(statuses[t.status]||t.status)+' · Ergebnis wird angezeigt …';}if(event.event==='error')streamError=event.message;if(event.event==='answer'){renderReply(reply,event);answerReceived=true;$('#chat-status').textContent=(event.traces||[]).some(t=>t.status==='needs_clarification')?'Rückfrage: Antworte unten im selben Eingabefeld.':`Antwort erhalten · Frage ${event.turns} von 20 in diesem Gespräch.`;}};
  try{
    const res=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({question,formulate:$('#natural-answer')?.checked===true}),signal:controller.signal});if(!res.ok){const data=await res.json();throw Error(data.message||'Anfrage fehlgeschlagen.');}
    const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done){buffer+=decoder.decode();break;}buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines)if(line.trim())receive(JSON.parse(line));}if(buffer.trim())receive(JSON.parse(buffer));if(streamError)throw Error(streamError);if(!answerReceived)throw Error('Verbindung unterbrochen. Bitte erneut versuchen.');
  }catch(error){const message=error.name==='AbortError'?'Anfrage abgebrochen.':error.message;reply.classList.add('error');reply.querySelector('.answer-text').textContent=message;$('#chat-status').textContent=message;$('#chat-question').value=question;if(/HTTP 40[13]/.test(message))$('#connection').open=true;}
  finally{controller=null;setBusy(false);$('#chat-question').focus();}
});
(async()=>{try{const state=await api('/api/session');csrf=state.csrf;ready(state.configured);$('#chat-status').textContent=state.configured?'Bereit. Schreibe eine Frage oder wähle ein Beispiel.':'Bitte zuerst deinen Swisscom-Schlüssel oben hinterlegen.';for(const item of state.messages||[]){bubble('user',item.question);renderReply(bubble('assistant',''),item);}}catch{$('#api-state').textContent='Server nicht erreichbar';$('#key-status').textContent='Bitte START-WINDOWS.cmd öffnen und das Startfenster geöffnet lassen.';$('#key-save').disabled=true;}})();

function quickReply(label,question){const b=make('button',label);b.type='button';b.className='secondary quick-reply';b.addEventListener('click',()=>{if(busy)return;$('#chat-question').value=question;$('#chat-form').requestSubmit();});return b;}
function locationMap(trace){
  const points=(trace.locations||[]).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));
  const origin=trace.origin&&Number.isFinite(trace.origin.lat)?trace.origin:null;
  const all=origin?[...points,origin]:points;
  const width=640,height=330,project=(p,z)=>{const scale=256*2**z,s=Math.sin(p.lat*Math.PI/180);return {x:(p.lon+180)/360*scale,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*scale};};
  let zoom=17;const boxAt=z=>{const p=all.map(x=>project(x,z));return {left:Math.min(...p.map(v=>v.x)),right:Math.max(...p.map(v=>v.x)),top:Math.min(...p.map(v=>v.y)),bottom:Math.max(...p.map(v=>v.y))};};
  while(zoom>10){const b=boxAt(zoom);if(b.right-b.left<width-100&&b.bottom-b.top<height-100)break;zoom--;}
  const box=make('section','');box.className='geo-map';box.append(make('h3',['city_subset','straight_line_subset'].includes(trace.sortMode)?'Städtische Recyclinghöfe für Haushaltsbatterien':origin?'Sammelstellen rund um deine Adresse':'Sammelstellen im gewählten Gebiet'));
  const ns='http://www.w3.org/2000/svg';const svg=(tag,attrs)=>{const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs||{}))n.setAttribute(k,String(v));return n;};
  const canvas=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':'Karte mit amtlichen Sammelstellen; nummerierte grüne Punkte und blauer Ausgangspunkt'});canvas.classList.add('map-canvas');
  const status=make('small','');status.className='map-status';
  const controls=make('div','');controls.className='map-controls';
  const minus=make('button','−'),plus=make('button','+');minus.type=plus.type='button';minus.setAttribute('aria-label','Karte verkleinern');plus.setAttribute('aria-label','Karte vergrössern');controls.append(minus,plus);
  function draw(){
   canvas.replaceChildren();status.textContent='Kartenhintergrund: OpenStreetMap. Grüne Zahlen entsprechen den Standorten.';
   const bounds=boxAt(zoom),left=(bounds.left+bounds.right-width)/2,top=(bounds.top+bounds.bottom-height)/2;
   for(let x=Math.floor(left/256);x<=Math.floor((left+width)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+height)/256);y++){
    const tile=svg('image',{x:x*256-left,y:y*256-top,width:256,height:256,href:`https://tile.openstreetmap.org/${zoom}/${x}/${y}.png`,referrerpolicy:'strict-origin-when-cross-origin'});
    tile.addEventListener('error',()=>{status.textContent='Kartenhintergrund nicht erreichbar. Die nummerierten Punkte und Standortlinks beruhen weiterhin auf amtlichen Koordinaten.';});canvas.append(tile);
   }
   function marker(p,label,color){const position=project(p,zoom),g=svg('g',{}),circle=svg('circle',{cx:position.x-left,cy:position.y-top,r:14,fill:color,stroke:'white','stroke-width':3});const title=svg('title',{});title.textContent=label==='A'?'Ausgangspunkt: '+p.address:p.address;const text=svg('text',{x:position.x-left,y:position.y-top+5,'text-anchor':'middle',fill:'white','font-size':13,'font-weight':'bold'});text.textContent=label;g.append(title,circle,text);canvas.append(g);}
   points.forEach((p,i)=>marker(p,String(i+1),'#17654d'));if(origin)marker(origin,'A','#2468a1');
   minus.disabled=zoom<=10;plus.disabled=zoom>=18;
  }
  minus.addEventListener('click',()=>{if(zoom>10){zoom--;draw();}});plus.addEventListener('click',()=>{if(zoom<18){zoom++;draw();}});
  box.append(canvas,controls,status);const credit=make('p','© ');credit.className='map-credit';credit.append(link('https://www.openstreetmap.org/copyright','OpenStreetMap-Mitwirkende'),document.createTextNode(' · Standorte/Adressen: Stadt Zürich, CC0 · '),link('https://www.openstreetmap.org/fixthemap','Kartenfehler melden'));box.append(credit);
  if(origin)box.append(make('small','A = amtlicher Adresspunkt. Luftlinie berücksichtigt keine Brücken, Strassenübergänge oder Eingänge.'));
  draw();return box;
}
